data:
  train: train.csv
  dev: dev.csv
  test: test.csv

bin_dir: models/lgb-model

pipeline:
  - type: tfidf
    args:
      tokenizer:
        type: mecab
        args:
          lemmatize: true
          exclude_pos:
            - 助詞
            - 助動詞
      max_features: 10000
      min_df: 3
      ngram_range:
        - 1
        - 3
  - type: lgb
