data:
  label_column: category
  text_column: title
  args:
    # path: shunk031/livedoor-news-corpus
    # random_state: 0
    # shuffle: true
    path: data/jsonl

output_dir: models/lstm-model

pipeline:
  - type: bunruija.feature_extraction.sequence.SequenceVectorizer
    args:
      tokenizer:
        type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
        args:
          lemmatize: false
      max_features: 30000
  - type: bunruija.classifiers.lstm.LSTMClassifier
    args:
      device: cpu
      batch_size: 8
      dim_emb: 256
      dim_hid: 512
      num_layers: 1
      optimizer:
        type: torch.optim.AdamW
        args:
          lr: 0.001
          betas:
            - 0.9
            - 0.999
          weight_decay: 0.01
      static_embedding_path: jawiki.all_vectors.300d.txt
      max_epochs: 3
