preprocess:
  data:
    train: train.csv
    dev: dev.csv
    test: test.csv

tokenizer:
  type: mecab
  args:
    lemmatize: false

bin_dir: models/lstm-model

classifier:
  - type: sequence
    args:
      max_features: 10000
  - type: lstm
    args:
      batch_size: 10
      dim_emb: 16
      dim_hid: 32
      optimizer: adamw
      static_embedding_path: jawiki.all_vectors.300d.txt
      lr: 0.001
      max_epochs: 10
      weight_decay: 0.01
