data:
  train: train.csv
  dev: dev.csv
  test: test.csv

tokenizer:
  type: mecab
  args:
    lemmatize: false

bin_dir: models/lstm-model

classifier:
  - type: sequence
    args:
      max_features: 30000
  - type: lstm
    args:
      device: cuda:0
      batch_size: 8
      dim_emb: 256
      dim_hid: 512
      num_layers: 1
      optimizer: adamw
#       static_embedding_path: jawiki.all_vectors.300d.txt
      lr: 0.001
      max_epochs: 10
      weight_decay: 0.01
