data:
  train: train.csv
  dev: dev.csv
  test: test.csv

bin_dir: models/lstm-model

pipeline:
  - type: bunruija.feature_extraction.sequence.SequenceVectorizer
    args:
      tokenizer:
        type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
        args:
          lemmatize: false
      max_features: 30000
  - type: bunruija.classifiers.lstm.LSTMClassifier
    args:
      device: cpu
      batch_size: 8
      dim_emb: 256
      dim_hid: 512
      num_layers: 1
      optimizer: adamw
      static_embedding_path: jawiki.all_vectors.300d.txt
      lr: 0.001
      max_epochs: 3
      weight_decay: 0.01
