preprocess:
  data:
    train: train.csv
    dev: dev.csv
    test: test.csv

tokenizer:
  type: mecab
  args:
    lemmatize: false

bin_dir: models/prado-model

classifier:
  - type: sequence
    args:
      max_features: 10000
  - type: prado
    args:
      batch_size: 10
      n_features: 512
      dim_emb: 64
      dim_hid: 64
      optimizer: adamw
      lr: 0.001
      max_epochs: 3
      weight_decay: 0.01
