data:
  train: train.csv
  dev: dev.csv
  test: test.csv

tokenizer:
  type: mecab
  args:
    lemmatize: false

bin_dir: models/prado-model

classifier:
  - type: sequence
    args:
      max_features: 30000
  - type: prado
    args:
      batch_size: 10
      n_features: 512
      dim_emb: 256
      dim_hid: 512
      optimizer: adamw
      lr: 0.001
      max_epochs: 10
      weight_decay: 0.01
      log_interval: 100
