data:
  train: train.csv
  dev: dev.csv
  test: test.csv

bin_dir: models/prado-model

pipeline:
  - type: bunruija.feature_extraction.sequence.SequenceVectorizer
    args:
      tokenizer:
        type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
        args:
          lemmatize: false
      max_features: 30000
  - type: bunruija.classifiers.prado.PRADO
    args:
      batch_size: 10
      n_features: 512
      dim_emb: 256
      dim_hid: 512
      optimizer: adamw
      lr: 0.001
      max_epochs: 3
      weight_decay: 0.01
      log_interval: 100
