data:
  train: train.csv
  dev: dev.csv
  test: test.csv

bin_dir: models/qrnn-model

pipeline:
  - type: sequence
    args:
    tokenizer:
      type: mecab
      args:
        lemmatize: false
      max_features: 30000
  - type: qrnn
    args:
      device: cuda:0
      batch_size: 32
      n_features: 512
      dim_emb: 512
      dim_hid: 1024
      num_layers: 2
      optimizer: adamw
      lr: 0.001
      max_epochs: 10
      weight_decay: 0.01
      log_interval: 100
