data:
  train: train.csv
  dev: dev.csv
  test: test.csv

output_dir: models/qrnn-model

pipeline:
  - type: bunruija.feature_extraction.sequence.SequenceVectorizer
    args:
      tokenizer:
        type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
        args:
          lemmatize: false
        max_features: 30000
  - type: bunruija.classifiers.qrnn.QRNN
    args:
      device: cpu
      batch_size: 32
      dim_emb: 128
      dim_hid: 256
      num_layers: 2
      max_epochs: 10
      optimizer:
        type: torch.optim.AdamW
        args:
          lr: 0.001
          betas:
            - 0.9
            - 0.999
          weight_decay: 0.01
      log_interval: 10
      static_embedding_path: jawiki.all_vectors.300d.txt
      num_workers: 2
