data:
  train: train.csv
  dev: dev.csv
  test: test.csv

output_dir: models/stacking-model

pipeline:
  - type: sklearn.ensemble.StackingClassifier
    args:
      estimators:
        - type: pipeline_0
          args:
            - type: sklearn.feature_extraction.text.TfidfVectorizer
              args:
                tokenizer:
                  type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
                  args:
                    lemmatize: true
                    exclude_pos:
                      - 助詞
                      - 助動詞
            - type: sklearn.svm.SVC
              args:
                C: 10.
        - type: pipeline_1
          args:
            - type: sklearn.feature_extraction.text.TfidfVectorizer
              args:
                tokenizer:
                  type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
            - type: sklearn.ensemble.RandomForestClassifier
        - type: pipeline_2
          args:
            - type: bunruija.feature_extraction.sequence.SequenceVectorizer
              args:
                tokenizer:
                  type: bunruija.tokenizers.mecab_tokenizer.MeCabTokenizer
            - type: bunruija.classifiers.lstm.LSTMClassifier
              args:
                device: cpu
                batch_size: 8
                dim_emb: 256
                dim_hid: 511
                num_layers: 1
      final_estimator:
        type: sklearn.svm.SVC
