data:
  train: train.csv
  dev: dev.csv
  test: test.csv

bin_dir: models/stacking-model

pipeline:
  - type: stacking
    args:
      estimators:
        - type: pipeline_0
          args:
            - type: tfidf
              args:
                tokenizer:
                  type: mecab
                  args:
                    lemmatize: true
                    exclude_pos:
                      - 助詞
                      - 助動詞
            - type: svm
              args:
                C: 10.
        - type: pipeline_1
          args:
            - type: tfidf
              args:
                tokenizer:
                  type: mecab
            - type: random_forest 
        - type: pipeline_2
          args:
            - type: sequence
              args:
                tokenizer:
                  type: mecab
            - type: lstm
              args:
                device: cpu
                batch_size: 8
                dim_emb: 256
                dim_hid: 511
                num_layers: 1
      final_estimator:
        type: svm
