preprocess:
  data:
    train: train.csv
    dev: dev.csv
    test: test.csv

bin_dir: models/transformer-model

tokenizer:
  type: auto
  args:
    from_pretrained: cl-tohoku/bert-base-japanese

classifier:
  - type: sequence
  - type: transformer
    args:
      from_pretrained: cl-tohoku/bert-base-japanese
      optimizer: adamw
      lr: 3e-5
      max_epochs: 3
      weight_decay: 0.01
