preprocess:
  data:
    train: train.csv
    dev: dev.csv
    test: test.csv

  tokenizer:
    type: mecab
    args:
      lemmatize: false

  vectorizer:
    type: sequence
    args:
      max_features: 10000

bin_dir: lstm-model

classifier:
  type: lstm
  args:
    batch_size: 10
    max_epochs: 10
    dim_emb: 64
    dim_hid: 256
    static_embedding_path: jawiki.all_vectors.300d.txt
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.01
